# -*- coding: utf-8 -*-
"""md5ofstring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ZiydzTCTiwKQbITjKN2kdrFOQGWWJiM
"""

text='hello world'
import hashlib
m=hashlib.md5()
m.update(text.encode('utf-8'))
print(m.hexdigest())
#5eb63bbbe01eeed093cb22bb8f5acdc3